In [413]:
import pandas as pd
import numpy as np
import pickle
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

In [414]:
data = pd.read_csv('reprocessed.hungarian.data',sep=" ",header=None)
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,40.0,1.0,2.0,140.0,289.0,0.0,0.0,172.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
1,49.0,0.0,3.0,160.0,180.0,0.0,0.0,156.0,0.0,1.0,2.0,-9.0,-9.0,1.0
2,37.0,1.0,2.0,130.0,283.0,0.0,1.0,98.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
3,48.0,0.0,4.0,138.0,214.0,0.0,0.0,108.0,1.0,1.5,2.0,-9.0,-9.0,3.0
4,54.0,1.0,3.0,150.0,-9.0,0.0,0.0,122.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,36.0,1.0,2.0,120.0,166.0,0.0,0.0,180.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
291,48.0,1.0,3.0,110.0,211.0,0.0,0.0,138.0,0.0,0.0,-9.0,-9.0,6.0,0.0
292,47.0,0.0,2.0,140.0,257.0,0.0,0.0,135.0,0.0,1.0,1.0,-9.0,-9.0,0.0
293,53.0,1.0,4.0,130.0,182.0,0.0,0.0,148.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
data.isnull().sum()

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
dtype: int64

In [415]:
data = data.dropna()

In [16]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,40.0,1.0,2.0,140.0,289.0,0.0,0.0,172.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
1,49.0,0.0,3.0,160.0,180.0,0.0,0.0,156.0,0.0,1.0,2.0,-9.0,-9.0,1.0
2,37.0,1.0,2.0,130.0,283.0,0.0,1.0,98.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
3,48.0,0.0,4.0,138.0,214.0,0.0,0.0,108.0,1.0,1.5,2.0,-9.0,-9.0,3.0
4,54.0,1.0,3.0,150.0,-9.0,0.0,0.0,122.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,48.0,0.0,2.0,-9.0,308.0,0.0,1.0,-9.0,-9.0,2.0,1.0,-9.0,-9.0,0.0
290,36.0,1.0,2.0,120.0,166.0,0.0,0.0,180.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
291,48.0,1.0,3.0,110.0,211.0,0.0,0.0,138.0,0.0,0.0,-9.0,-9.0,6.0,0.0
292,47.0,0.0,2.0,140.0,257.0,0.0,0.0,135.0,0.0,1.0,1.0,-9.0,-9.0,0.0
293,53.0,1.0,4.0,130.0,182.0,0.0,0.0,148.0,0.0,0.0,-9.0,-9.0,-9.0,0.0

In [21]:
x = np.array(data.drop(13,axis=1))
y = np.array(data[13])

In [34]:
xTrain,xTest,yTrain,yTest = train_test_split(x,y,test_size=0.1)

In [29]:
modelOne = LogisticRegression()
modelOne.fit(xTrain,yTrain)
prediction = modelOne.predict(xTest)
acc = accuracy_score(prediction,yTest)

c:\Users\Ajay\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [31]:
print(acc)

0.6333333333333333

In [402]:
modelTwo = RandomForestClassifier()
best = 0
for i in range(50):
    xTrain,xTest,yTrain,yTest = train_test_split(x,y,test_size=0.1)
    modelTwo.fit(xTrain,yTrain)
    prediction = modelTwo.predict(xTest)
    acc = accuracy_score(prediction,yTest)
    if acc>best:
        best=acc
        with open("model.pickle",'wb') as file:
            pickle.dump(modelTwo,file)

In [403]:
print(best)

0.8333333333333334

In [1]:
'''modelThree = KNeighborsClassifier(n_neighbors=9)

best = 0
for i in range(900):
    xTrain,xTest,yTrain,yTest = train_test_split(x,y,test_size=0.1)
    modelThree.fit(xTrain,yTrain)
    prediction = modelThree.predict(xTest)
    acc = accuracy_score(prediction,yTest)
    if acc>best:
        best=acc
        with open("model.pickle",'wb') as file:
            pickle.dump(modelThree,file)
print(best)'''

'modelThree = KNeighborsClassifier(n_neighbors=9)\n\nbest = 0\nfor i in range(900):\n    xTrain,xTest,yTrain,yTest = train_test_split(x,y,test_size=0.1)\n    modelThree.fit(xTrain,yTrain)\n    prediction = modelThree.predict(xTest)\n    acc = accuracy_score(prediction,yTest)\n    if acc>best:\n        best=acc\n        with open("model.pickle",\'wb\') as file:\n            pickle.dump(modelThree,file)\nprint(best)'

In [416]:
xTrain,xTest,yTrain,yTest = train_test_split(x,y,test_size=0.1)
with open("model.pickle",'rb') as file:
    model = pickle.load(file)
acc = accuracy_score(model.predict(xTest),yTest)
print(acc)

0.9666666666666667